$(document).ready(function() {
    // bibtex
    var editor = CodeMirror.fromTextArea(document.getElementById("bibtex"), {
        lineNumbers: false,
        lineWrapping: true,
        readOnly:true
    });

    // generated code
    var codegen_html_template = `
<p>Code generated by our Language Model Program (<a href="{link}">raw text file</a>):</p>
<pre class="codegen"><code class="language-python">{code}</code></pre>`;
    $('[id^="code_"]').each(function() {
        var id = this.id;
        domain_name_cmd_idx = id.substring(5);
        var sep_idx = domain_name_cmd_idx.indexOf('_');
        var domain_name = domain_name_cmd_idx.substring(0, sep_idx);
        var cmd_idx_str = domain_name_cmd_idx.substring(sep_idx + 1);

        var codegen_file = '/codegen/' + domain_name + '/' + cmd_idx_str + '.txt';
        $.get(codegen_file, function(data) {
            var highlighted_code = hljs.highlight(data, {language: 'python'}).value;
            var html_code = codegen_html_template
                                .replace('{code}', highlighted_code)
                                .replace('{link}', codegen_file);
            $(html_code).appendTo("#" + id);
         }, 'text');
    });

    var current_cmd_idxs = {
        "linereal": 1,
        "linesim": 1,
        "pairreal": 1,
        "pairsim": 1,
        "areareal": 1,
        "areasim": 1,
        "fractal": 1,
        "aloha": 1,
        "chest": 1,
        "stonehoe": 1,
        "minecart":1,
        "acaciatrapdoor":1,
        "compass":1,
        "cookedchicken":1,
        "diamondchestplate":1,
        "diamondpickaxe":1,
        "goldenpickaxe":1,
        "painting":1,
        "smoker":1,
    }

    var vid_start_times = {
        "smoker": {
            1:0,
            2:16,
            3:20,
            4:24,
            5:27,
            6:38,
            7:59,
            8:70
        },
        "painting": {
            1:0,
            2:5,
            3:13,
            4:17,
            5:20,
            6:23,
        },
        "goldenpickaxe": {
            1:0,
            2:12,
            3:16,
            4:20,
            5:25,
            6:35,
            7:62,
            8:71,
            9:83,
            10:234,
            11:276,
            12:284,
            13:360,
            14:410
        },
        "diamondpickaxe": {
            1:0,
            2:21,
            3:25,
            4:29,
            5:32,
            6:47,
            7:69,
            8:79,
            9:94,
            10:112,
            11:159,
            12:170,
            13:352,
        },
        "diamondchestplate": {
            1:0,
            2:37,
            3:41,
            4:45,
            5:49,
            6:67,
            7:81,
            8:95,
            9:108,
            10:265,
            11:293,
            12:317,
            13:464,
        },
        "cookedchicken": {
            1:0,
            2:8,
            3:18,
            4:23,
            5:27,
            6:29,
            7:43,
            8:59,
            9:70
            },
        "compass": {
            1:0,
            2:14,
            3:18,
            4:21,
            5:26,
            6:37,
            7:66,
            8:79,
            9:90,
            10:109,
            11:157,
            12:169,
            13:175,
            14:232,
            15:467
        },
        "acaciatrapdoor": {
            1:0,
            2:26,
            3:29,
            4:33
        },
        "chest": {
            1: 0,
            2: 5,
            3: 7,
            4: 11,
        },
        "stonehoe": {
            1:0,
            2:9,
            3:13,
            4:16,
            5:19,
            6:26,
            7:36,
        },
        "minecart": {
            1:0,
            2:27,
            3:31,
            4:35,
            5:38,
            6:49,
            7:93,
            8:102,
            9:113,
            10:152,
            11:207,
        },        
        "linereal": {
            1: 0,
            2: 1,
            3: 2,
            4: 3,
            5: 4,
            6: 5,
            7: 6,
            8: 7,
            9: 8,
            10: 9,
        },
        "linesim": {
            1: 0,
            2: 1,
            3: 2,
            4: 3,
            5: 4,
            6: 5,
            7: 6,
            8: 7,
            9: 8,
            10: 9,
            11: 10,
            12: 11,
            13: 12,
            14: 13,
            15: 14,
            16: 15,
        },
        "pairreal": {
            1: 0,
            2: 1,
            3: 2,
            4: 3,
            5: 4,
            6: 5,
            7: 6,
            8: 7,
        },
        "pairsim": {
            1: 0,
            2: 1,
            3: 2,
            4: 3,
            5: 4,
            6: 5,
            7: 6,
            8: 7,
        },
        "areareal": {
            1: 0,
            2: 1,
            3: 2,
            4: 3,
            5: 4,
            6: 5,
            7: 6,
            8: 7,
            9: 8,
            10: 9,
            11: 10,
            12: 11,
        },
        "areasim": {
            1: 0,
            2: 1,
            3: 2,
            4: 3,
            5: 4,
            6: 5,
            7: 6,
            8: 7,
            9: 8,
            10: 9,
            11: 10,
            12: 11,
            13: 12,
            14: 13,
        },
        "fractal": {
            1: 0,
            2: 2,
            3: 4,
            4: 6,
        },
        "aloha": {
            1: 0,
            2: 3,
            3: 6,
            4: 9,
            5: 12,
            6: 15,
            7: 18,
            8: 21,
            9: 24,
            10: 27,
            11: 30,
            12: 33,
            13: 36,
        },
    }

    var vid_end_times = {
        "smoker": {
            1:16,
            2:20,
            3:24,
            4:27,
            5:38,
            6:59,
            7:70,
            8:78
        },
        "painting": {
            1:5,
            2:13,
            3:17,
            4:20,
            5:23,
            6:35,
        },
        "goldenpickaxe": {
            1:12,
            2:16,
            3:20,
            4:25,
            5:35,
            6:62,
            7:71,
            8:83,
            9:234,
            10:276,
            11:284,
            12:360,
            13:410,
            14:415,
        },
        "diamondpickaxe": {
            1:21,
            2:25,
            3:29,
            4:32,
            5:47,
            6:69,
            7:79,
            8:94,
            9:112,
            10:159,
            11:170,
            12:352,
            13:360,
        },
        "diamondchestplate": {
            1:37,
            2:41,
            3:45,
            4:49,
            5:67,
            6:81,
            7:95,
            8:108,
            9:265,
            10:293,
            11:317,
            12:464,
            13:471,
        },
        "cookedchicken": {
            1:8,
            2:18,
            3:23,
            4:27,
            5:29,
            6:43,
            7:59,
            8:70,
            9:98,
        },
        "compass": {
            1:14,
            2:18,
            3:21,
            4:26,
            5:37,
            6:66,
            7:79,
            8:90,
            9:109,
            10:157,
            11:169,
            12:175,
            13:232,
            14:467,
            15:482,
        },
        "acaciatrapdoor": {
            1:26,
            2:29,
            3:33,
            4:44
        },
        "chest": {
            1: 5,
            2: 7,
            3: 11,
            4: 18,
        },
        "stonehoe": {
            1:9,
            2:13,
            3:16,
            4:19,
            5:26,
            6:36,
            7:47
        },
        "minecart": {
            1:27,
            2:31,
            3:35,
            4:38,
            5:49,
            6:93,
            7:102,
            8:113,
            9:152,
            10:207,
            11:226,
        },    
        "linereal": {
            1: 1,
            2: 2,
            3: 3,
            4: 4,
            5: 5,
            6: 6,
            7: 7,
            8: 8,
            9: 9,
            10:10,
        },
        "linesim": {
            1: 1,
            2: 2,
            3: 3,
            4: 4,
            5: 5,
            6: 6,
            7: 7,
            8: 8,
            9: 9,
            10:10,
            11:11,
            12:12,
            13:13,
            14:14,
            15:15,
            16:16,
        },
        "pairreal": {
            1: 1,
            2: 2,
            3: 3,
            4: 4,
            5: 5,
            6: 6,
            7: 7,
            8: 8,
        },
        "pairsim": {
            1: 1,
            2: 2,
            3: 3,
            4: 4,
            5: 5,
            6: 6,
            7: 7,
            8: 8,
        },
        "areareal": {
            1: 1,
            2: 2,
            3: 3,
            4: 4,
            5: 5,
            6: 6,
            7: 7,
            8: 8,
            9: 9,
            10:10,
            11:11,
            12:12,
        },
        "areasim": {
            1: 1,
            2: 2,
            3: 3,
            4: 4,
            5: 5,
            6: 6,
            7: 7,
            8: 8,
            9: 9,
            10:10,
            11:11,
            12:12,
            13:13,
            14:14,
        },
        "fractal": {
            1: 2,
            2: 4,
            3: 6,
            4: 8,
        },
        "aloha": {
            1: 3,
            2: 6,
            3: 9,
            4: 12,
            5: 15,
            6: 18,
            7: 21,
            8: 24,
            9: 27,
            10: 30,
            11: 33,
            12: 36,
            13: 39,
        },
    }

    function playSeg(vid, start_time, end_time, domain_name, desired_cmd_idx) {
        vid.play();
        vid.pause();
        vid.currentTime = start_time;
        vid.play();

        // console.log("start and end: " + start_time.toString() + ", " + end_time.toString());

        var pausing_function = function() {
            // console.log("checking pausing function cb for " + domain_name);
            // console.log("current and end time");
            // console.log(this.currentTime);
            // console.log(end_time)
            if (this.currentTime >= end_time) {
                // console.log("reached end time");
                this.pause();
                this.removeEventListener("timeupdate", pausing_function);
            }
        };

        // console.log("adding timeupdate pausing_function for " + domain_name + "_" + desired_cmd_idx.toString());
        vid.addEventListener("timeupdate", pausing_function);
    }

    // demos
    $('select').on('change', function() {
        var sep_idx = this.value.indexOf('_');
        var domain_name = this.value.substring(0, sep_idx);
        var desired_cmd_idx = parseInt(this.value.substring(sep_idx + 1));
        var current_cmd_idx = current_cmd_idxs[domain_name];
        
        // hide current content
        var current_content = $('#content_' + domain_name + "_" + current_cmd_idx.toString());
        current_content.hide();

        // show desired content
        var desired_content = $('#content_' + domain_name + "_" + desired_cmd_idx.toString());
        desired_content.show();

        // switch videos
        if (domain_name.startsWith("mobile")) {
            var current_vid = $('#vid_1_' + domain_name + "_" + current_cmd_idx.toString()).get(0);
            var desired_vid = $('#vid_1_' + domain_name + "_" + desired_cmd_idx.toString()).get(0);
            current_vid.pause();
            desired_vid.play();
        } else {
            var vid = $("#vid_" + domain_name)[0];
            var start_time = vid_start_times[domain_name][desired_cmd_idx];
            var end_time = vid_end_times[domain_name][desired_cmd_idx];
            playSeg(vid, start_time, end_time, domain_name, desired_cmd_idx);
        }

        // set current to desired
        current_cmd_idxs[domain_name] = desired_cmd_idx;
    });
});
